### ISSUE TITLE
Script causes infinite reload loop on steamcommunity.com/openid/login

### ISSUE THREAD

**Issue by DFNCTSC** [gekkedev/giveawayHelperEnhancer#1]
Just started happening today. When loading the Steam login URL for OpenID it just refreshes forever and doesn't allow logging in to any site.

**Comment by gekkedev** [comment]
Is this still happening? I cannot reproduce it. It might happen when a website is not accepting the login request (this might be temporary) and forwards back to Steam to log in again.
If it's happening with a specific site I can test it and figure something out.

**Comment by gekkedev** [comment]
@DFNCTSC I'll close this for now. Feel free to come back (with more information on how to reproduce it) at any time.
