### ISSUE TITLE
[Site] goldengiveaways.org

### ISSUE THREAD

**Issue by nihaals** [gekkedev/giveawayHelperEnhancer#2]
Example: https://goldengiveaways.org/giveaways/show/54

**Comment by gekkedev** [comment]
Thanks for the hint, it's now fully implemented with autologin and autosolving. Make sure to let Tamper-/Greasemonkey check for updates.

**Comment by nihaals** [comment]
Thanks for such a fast update!

**Comment by gekkedev** [comment]
You're welcome. Feel free to report any issues or suggestions 👍
