### ISSUE TITLE
[Site] bananagiveaway.com

### ISSUE THREAD

**Issue by nihaals** [gekkedev/giveawayHelperEnhancer#3]
Example: https://www.bananagiveaway.com/giveaway/37

**Comment by gekkedev** [comment]
Added login and ad removal. The "get X points"-tasks are really annoying. That way you're paying them multiple times the money that a key would cost. If we had a mail address of an account with many points we could try to see if it can be used by multiple people, because then auto-solving could be implemented. Other task types are easier to solve though, just by visiting given links.
Keeping the issue open for further discussion.

**Comment by nihaals** [comment]
Yeah, so far if it's had the points one then I don't do it, but if someone's already got an account that would help a lot

**Comment by nihaals** [comment]
How do you actually "trigger" it? I'm on a new giveaway, yet nothing's running

**Comment by gekkedev** [comment]
Most tasks can be solved by visiting two links hidden in the site's markup. Then, you just have to reload the page. I'm adding that for all tasks where I see that it is possible, but we cannot get past the point-centric ones. The next version will (for other reasons) be too experimental to send it out as update to all users, so it might take a while.
Meanwhile on https://github.com/gekkedev/giveawayHelperEnhancer/issues/4 the ad removal is quite a struggle but might be fixed soon once the new version gets released.

**Comment by gekkedev** [comment]
Updated it anyway. There is a task type asking you to comment somewhere, it might be based on link-visiting and can be added easily once this theory is proven. Leaving this open until a new giveaway pops up.

**Comment by nihaals** [comment]
https://www.bananagiveaway.com/giveaway/67 - Not skipping any, but getting a message
![image](https://user-images.githubusercontent.com/18350092/38171700-de75d4d0-3596-11e8-9ed4-bee0770f1a9c.png)

**Comment by gekkedev** [comment]
Updated (https://github.com/gekkedev/giveawayHelperEnhancer/commit/7b6a4277f9f959f5606908bba61069dc4e9042fd). They changed some labellings, and the script relied on specific keywords like "like" or "share" instead of picking task types by the icons.
BTW if there are any error-lookalikes appearing in the browser console, feel free to add them to the issues.

**Comment by nihaals** [comment]
It just redirects to https://www.bananagiveaway.com/giveaway/steam, which gives:
```
Cannot send headers; headers already sent in /home/bananagiveaway/public_html/_____protected_____/library/Next/Action/Controller.php, line 99#0 /home/bananagiveaway/public_html/_____protected_____/library/Zend/Controller/Response/Abstract.php(115): Zend_Controller_Response_Abstract->canSendHeaders(true) #1 /home/bananagiveaway/public_html/_____protected_____/application/controllers/ErrorController.php(6): Zend_Controller_Response_Abstract->setHeader('Content-Type', 'text/html; char...') #2 /home/bananagiveaway/public_html/_____protected_____/library/Zend/Controller/Action.php(516): ErrorController->errorAction() #3 /home/bananagiveaway/public_html/_____protected_____/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('errorAction') #4 /home/bananagiveaway/public_html/_____protected_____/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http)) #5 /home/bananagiveaway/public_html/index.php(100): Zend_Controller_Front->dispatch() #6 {main}

**Comment by gekkedev** [comment]
The login seems to be not working anymore on that site. The error code is telling us about a beginner mistake done on server side. 🤣

**Comment by nihaals** [comment]
https://www.bananagiveaway.com/giveaway/71

**Comment by gekkedev** [comment]
It skips 4 tasks for me, it just takes some time to go through them all. Didn't it work or you?

**Comment by nihaals** [comment]
Skipped a whole 0

**Comment by nihaals** [comment]
No errors in console either

**Comment by gekkedev** [comment]
Which browser are you using?
Could you post any output in the console even if it doesn't look like an error? The taskskipper should show a number of how many skippable tasks were found.

**Comment by nihaals** [comment]
`4 skippable tasks found.`
`Could not solve all solveable tasks!`
And I think this is from it too:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.bananatic.com/p/grabthegame. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.facebook.com/GrabTheGames/videos/2258929920914705/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

**Comment by gekkedev** [comment]
Well, the other output is related to the site. Which browser/extension?

**Comment by nihaals** [comment]
Firefox, Tampermonkey

**Comment by nihaals** [comment]
Yeah, it doesn't want to work on any of the giveaways, possibly a tampermonkey issue?

**Comment by gekkedev** [comment]
Sorry for no answer, I've been on it but noticed some things which need to be changed. The difficult thing here is to securely determine if a task is solved. If a task is somehow not being solved, it could cause infinite reloading. Without this problem, half of all supported websites would have a tasksolver alresdy. 

The solution would probably be to have a system which saves any task that was attempted to solve, and then use this as reference to prevent multiple attempts in case of tasks which cannot be solved automatically. That might take a lot of time, but luckily the weekend is coming! 😀

**Comment by gekkedev** [comment]
There have been some changes regarding bananagiveaway, this repository won't receive any feature updates anymore.
The successor is [here](https://github.com/gekkedev/GiveawayKiller/commit/7c555a51924bfe02e9f4d5b74f479a6fa29c4207)

**Comment by nihaals** [comment]
That link is a 404

**Comment by gekkedev** [comment]
Edited, thanks for the hint.
