### ISSUE TITLE
[Site] https://gamehag.com

### ISSUE THREAD

**Issue by nihaals** [gekkedev/giveawayHelperEnhancer#4]
Example: https://gamehag.com/giveaway/161

**Comment by gekkedev** [comment]
Ad removal implemented since https://github.com/gekkedev/giveawayHelperEnhancer/commit/4dc37b9c2adfa3689aacc2b324c7518b6985229e, and autologin afaik wasn't possible via steam. There's still a lot of auto-solving potential to be worked on another day! 😉 Keeping the issue open as reminder.

**Comment by iamJayed** [comment]
You May get Free CSGO skins at https://gamersnab.com/
